markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title: wushuangyang Blog
tagline: 'wushuangyang Personal Blog'
baseurl: /

author: wushuangyang
name: wushuangyang

#description: 'втси'

paginate:  5
recent-num: 5
article_num: 5
